spring:
  application:
    name: interview-task

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/
      username: interviewer
      password: three_tasks

  server:
    port: 8082